/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Admin {
  created_at: Generated<string>;
  email: string;
  first_name: string;
  id: string | null;
  last_name: string;
  middle_name: string | null;
  password_hash: string;
  role: Generated<string>;
  updated_at: Generated<string>;
  username: string;
}

export interface Routes {
  created_at: Generated<string>;
  fare: number;
  id: string | null;
  name: string;
  operator: string;
  updated_at: Generated<string>;
}

export interface RouteShapePoints {
  created_at: Generated<string>;
  id: string | null;
  latitude: number;
  longitude: number;
  route_id: string | null;
  sequence: number;
  updated_at: Generated<string>;
}

export interface RouteStops {
  created_at: Generated<string>;
  id: string | null;
  route_id: string | null;
  sequence: number;
  stop_id: string | null;
  updated_at: Generated<string>;
}

export interface Stops {
  created_at: Generated<string>;
  id: string | null;
  latitude: number;
  longitude: number;
  name: string;
  updated_at: Generated<string>;
}

export interface DB {
  admin: Admin;
  route_shape_points: RouteShapePoints;
  route_stops: RouteStops;
  routes: Routes;
  stops: Stops;
}
